# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=13
group=com.mars.blastingsand
java_version=17
deimos_version=2.7
# Common
mod_name=Smelting Sand in a Blast Furnace
mod_author=Mars
mod_id=blastingsand
license=MIT
homepage=https://modrinth.com/mod/smelting-sand-in-blast-furnace
description=Smelt Sand in the Blast Furnace
minecraft_version=1.18.2
modmenu_version=3.2.5
minecraft_version_range=[1.18, 1.19)
# Fabric
fabric_version=0.77.0+1.18.2
fabric_loader_version=0.16.9
# Forge
forge_version=40.3.0
forge_loader_version_range=[38,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
